server:
  port: 8085

spring:
  application:
    name: dolphin-workflow
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: eric
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
#    driver: com.mysql.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/activity?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    jdbc-url: ${spring.datasource.activiti.url}
#    username: eric
#    password: 123456
#    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true
    check-process-definitions: false
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
swagger:
  enable: true